// -------------------------------------------------------------------------
// PORTFOLIO MASTER AGGREGATOR
// -------------------------------------------------------------------------
// DO NOT EDIT THIS FILE DIRECTLY TO CHANGE CONTENT.
//
// -> EDIT PROJECTS HERE: src/data/projects.js
// -> EDIT PROFILE HERE:  src/data/profile.js
// -------------------------------------------------------------------------

import { projects } from '../src/data/projects.js';
import { profile, skills } from '../src/data/profile.js';
import { ui } from '../src/data/ui.js';

export const portfolioData = {
  profile,
  skills,
  projects,
  ui
};

export default portfolioData;